### ISSUE TITLE
Unable to upload logs without valid GPS data

### ISSUE THREAD

**Issue by lvale** [dronekit/droneshare#156]
I was trying to upload some indoor testing logs (without GPS) but the manual page http://www.droneshare.com/vehicle/731

throws out an error of :

Invalid location data was found in that log, ignoring

Local computer is MacBook Pro running Yosemite and latest Safari. but the same happens with Chrome.

Shouldn't it allow to parse this kind of logs without GPS data ??

**Comment by lvale** [comment]
Also APM Planner 2.0.17 is unable to upload indoor flights, because of the location issue
![screen shot 2015-05-26 at 16 49 34](https://cloud.githubusercontent.com/assets/3130363/7816634/6098394e-03c7-11e5-8749-416d56bd4616.png)

**Comment by AndKe** [comment]
I have examples of normal flights where the message is shown for no apparent reason - logs does have valid GPS fix at all time.

**Comment by mrpollo** [comment]
thanks @lvale @AndKe I think we already identified the issue and will be deploying a fix shortly, as soon as that happen I'll update this issue
